name: Publish

on:
  release:
    types:
      - published

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build
        run: |
          rm -rf dist
          uv build

      - name: Check package
        run: uv run --with twine twine check dist/*

      - name: Publish
        run: uv publish
